apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kubearena
  name: workshop
spec:
  replicas: 3
  selector:
    app: workshop
  template:
    metadata:
      labels:
        app: workshop
    spec:
      containers:
        - image: mewse/kubearena-workshop:1.0
          name: workshop
---
apiVersion: v1
kind: Service
metadata:
  name: workshop
spec:
  ports:
    - name: http
      port: 5000
      nodePort: 30001
  selector:
    app: workshop
  type: NodePort
